CREATE TABLE Posto_retirada (
  ID_posto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  endereco VARCHAR(150),
  telefone VARCHAR(11),
  email VARCHAR(50),
  geom GEOMETRY(Point,4326)
);


CREATE TABLE Usuarios (
  ID_User INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Name VARCHAR(50),
  email VARCHAR(50),
  Senha_hash VARCHAR(50),
  data_cadastro DATE,
  is_admin BOOLEAN,
  senha_temporaria BOOLEAN DEFAULT FALSE
);

CREATE TABLE Imagem_objeto (
  ID_imagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caminho_imagem VARCHAR(50),
  ID_objeto INTEGER
);

CREATE TABLE Objeto (
  ID_objeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  descricao VARCHAR(50),
  status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',

  Imagem_objeto_ID_imagem INTEGER,

  CONSTRAINT chk_objeto_status
    CHECK (status IN ('DISPONIVEL', 'DEVOLVIDO', 'DESCARTADO')),

  CONSTRAINT fk_objeto_imagem
    FOREIGN KEY (Imagem_objeto_ID_imagem)
    REFERENCES Imagem_objeto(ID_imagem)
);



CREATE TABLE objeto_perdido (
  ID_objeto INTEGER PRIMARY KEY,

  data_perda DATE,
  endereco_perda VARCHAR(150),
  geom_perdido GEOMETRY(Point,4326),

  CONSTRAINT fk_perdido_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE
);

CREATE TABLE objeto_achado (
  ID_objeto INTEGER PRIMARY KEY,

  data_encontro DATE,
  endereco_encontro VARCHAR(150),

  geom_achado GEOMETRY(Point,4326),

  geom_atual GEOMETRY(Point,4326),

  Posto_retirada_ID_posto INTEGER,

  CONSTRAINT fk_achado_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE,

  CONSTRAINT fk_achado_posto
    FOREIGN KEY (Posto_retirada_ID_posto)
    REFERENCES Posto_retirada(ID_posto)
);


CREATE TABLE Categoria (
  ID_categoria INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  descricao VARCHAR(150)
);

CREATE TABLE Objeto_Categoria (
  ID_objeto INTEGER,
  ID_categoria INTEGER,

  CONSTRAINT pk_Objeto_Categoria PRIMARY KEY (ID_objeto, ID_categoria),

  CONSTRAINT fk_objeto_categoria_objeto
    FOREIGN KEY (ID_objeto) REFERENCES Objeto(ID_objeto),

  CONSTRAINT fk_objeto_categoria_categoria
    FOREIGN KEY (ID_categoria) REFERENCES Categoria(ID_categoria)
);


/*Atualizar Imagens*/

ALTER TABLE Imagem_objeto
ADD COLUMN ID_objeto INTEGER;

UPDATE Imagem_objeto io
SET ID_objeto = o.ID_objeto
FROM Objeto o
WHERE o.Imagem_objeto_ID_imagem = io.ID_imagem;

ALTER TABLE Imagem_objeto
ADD CONSTRAINT fk_imagem_objeto
FOREIGN KEY (ID_objeto)
REFERENCES Objeto(ID_objeto)
ON DELETE CASCADE;




DROP VIEW view_objeto_achado_map;

DROP VIEW view_objeto_perdido_map;

ALTER TABLE Objeto
DROP CONSTRAINT fk_objeto_imagem;

ALTER TABLE Objeto
DROP COLUMN Imagem_objeto_ID_imagem;



/*-----------------------------------------------------------------------------------------------------*/
/* VIEWS */

DROP VIEW view_objeto_achado_map;

CREATE VIEW view_objeto_achado_map AS
SELECT
  oa.ID_objeto,

  o.nome,
  o.descricao,
  o.status,

  io.ID_imagem,
  io.caminho_imagem,

  oa.data_encontro,
  oa.endereco_encontro,

  oa.geom_achado

FROM objeto_achado oa

JOIN Objeto o
  ON o.ID_objeto = oa.ID_objeto

LEFT JOIN Imagem_objeto io
  ON io.ID_objeto = o.ID_objeto;

DROP VIEW view_objeto_perdido_map;

CREATE VIEW view_objeto_perdido_map AS
SELECT
  op.ID_objeto,

  o.nome,
  o.descricao,
  o.status,

  io.ID_imagem,
  io.caminho_imagem,

  op.data_perda,
  op.endereco_perda,

  op.geom_perdido

FROM objeto_perdido op

JOIN Objeto o
  ON o.ID_objeto = op.ID_objeto

LEFT JOIN Imagem_objeto io
  ON io.ID_objeto = o.ID_objeto;


CREATE OR REPLACE VIEW view_posto_retirada_map AS
SELECT
  p.ID_posto,

  p.nome,
  p.endereco,
  p.telefone,
  p.email,

  p.geom

FROM Posto_retirada p;


