/* ========================= */
/* POSTO DE RETIRADA */
/* ========================= */

CREATE TABLE Posto_retirada (
  ID_posto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  endereco VARCHAR(150),
  telefone VARCHAR(11),
  email VARCHAR(50),
  geom GEOMETRY(Point,4326)
);

/* ========================= */
/* USUÁRIOS */
/* ========================= */

CREATE TABLE Usuarios (
  ID_User INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  Name VARCHAR(50),
  email VARCHAR(50),
  Senha_hash VARCHAR(255),
  data_cadastro DATE,
  is_admin BOOLEAN,
  senha_temporaria BOOLEAN DEFAULT FALSE
);

/* ========================= */
/* OBJETO BASE */
/* ========================= */

CREATE TABLE Objeto (
  ID_objeto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  descricao VARCHAR(50),

  status VARCHAR(20) NOT NULL DEFAULT 'DISPONIVEL',

  CONSTRAINT chk_objeto_status
    CHECK (
      status IN (
        'PERDIDO',
        'DISPONIVEL',
        'DEVOLVIDO',
        'DESCARTADO'
      )
    )
);

/* ========================= */
/* IMAGENS DO OBJETO */
/* ========================= */

CREATE TABLE Imagem_objeto (
  ID_imagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  caminho_imagem VARCHAR(255),

  ID_objeto INTEGER,

  CONSTRAINT fk_imagem_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE
);

/* ========================= */
/* OBJETO PERDIDO */
/* ========================= */

CREATE TABLE objeto_perdido (
  ID_objeto INTEGER PRIMARY KEY,

  data_perda DATE,
  endereco_perda VARCHAR(150),
  geom_perdido GEOMETRY(Point,4326),

  CONSTRAINT fk_perdido_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE
);

/* ========================= */
/* OBJETO ACHADO */
/* ========================= */

CREATE TABLE objeto_achado (
  ID_objeto INTEGER PRIMARY KEY,

  data_encontro DATE,
  endereco_encontro VARCHAR(150),

  geom_achado GEOMETRY(Point,4326),
  geom_atual GEOMETRY(Point,4326),

  Posto_retirada_ID_posto INTEGER,

  CONSTRAINT fk_achado_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE,

  CONSTRAINT fk_achado_posto
    FOREIGN KEY (Posto_retirada_ID_posto)
    REFERENCES Posto_retirada(ID_posto)
);

/* ========================= */
/* CATEGORIA */
/* ========================= */

CREATE TABLE Categoria (
  ID_categoria INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  nome VARCHAR(50),
  descricao VARCHAR(150)
);

/* ========================= */
/* OBJETO - CATEGORIA (N:N) */
/* ========================= */

CREATE TABLE Objeto_Categoria (
  ID_objeto INTEGER,
  ID_categoria INTEGER,

  CONSTRAINT pk_objeto_categoria PRIMARY KEY (ID_objeto, ID_categoria),

  CONSTRAINT fk_objeto_categoria_objeto
    FOREIGN KEY (ID_objeto)
    REFERENCES Objeto(ID_objeto)
    ON DELETE CASCADE,

  CONSTRAINT fk_objeto_categoria_categoria
    FOREIGN KEY (ID_categoria)
    REFERENCES Categoria(ID_categoria)
    ON DELETE CASCADE
);

/* ========================= */
/* VIEWS */
/* ========================= */

CREATE VIEW view_objeto_achado_map AS
SELECT
  oa.ID_objeto,
  o.nome,
  o.descricao,
  o.status,
  oa.data_encontro,
  oa.endereco_encontro,
  oa.geom_achado,

  ARRAY_AGG(io.caminho_imagem) AS imagens

FROM objeto_achado oa
JOIN Objeto o ON o.ID_objeto = oa.ID_objeto
LEFT JOIN Imagem_objeto io ON io.ID_objeto = o.ID_objeto
GROUP BY
  oa.ID_objeto,
  o.nome,
  o.descricao,
  o.status,
  oa.data_encontro,
  oa.endereco_encontro,
  oa.geom_achado;


/* ========================= */

CREATE VIEW view_posto_retirada_map AS
SELECT
  p.ID_posto,
  p.nome,
  p.endereco,
  p.telefone,
  p.email,
  p.geom
FROM Posto_retirada p;


/* ========================= */

CREATE VIEW view_objeto_perdido_map AS
SELECT
  op.ID_objeto,
  o.nome,
  o.descricao,
  o.status,

  op.data_perda,
  op.endereco_perda,

  ST_Buffer(op.geom_perdido::geography, 300)::geometry AS geom_area,
  op.geom_perdido AS geom_ponto,

  ARRAY_AGG(io.caminho_imagem)
    FILTER (WHERE io.caminho_imagem IS NOT NULL) AS imagens

FROM objeto_perdido op
JOIN Objeto o ON o.ID_objeto = op.ID_objeto
LEFT JOIN Imagem_objeto io ON io.ID_objeto = o.ID_objeto

GROUP BY
  op.ID_objeto,
  o.nome,
  o.descricao,
  o.status,
  op.data_perda,
  op.endereco_perda,
  op.geom_perdido;


  CREATE TABLE Imagem_posto (
  ID_imagem INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  caminho_imagem VARCHAR(255),

  ID_posto INTEGER NOT NULL,

  CONSTRAINT fk_imagem_posto
    FOREIGN KEY (ID_posto)
    REFERENCES Posto_retirada(ID_posto)
    ON DELETE CASCADE
);


ALTER TABLE objeto_achado
DROP CONSTRAINT fk_achado_posto;

ALTER TABLE objeto_achado
ADD CONSTRAINT fk_achado_posto
FOREIGN KEY (Posto_retirada_ID_posto)
REFERENCES Posto_retirada(ID_posto)
ON DELETE SET NULL;


ALTER TABLE Objeto
ADD COLUMN ID_User INTEGER;

ALTER TABLE Objeto
ADD CONSTRAINT fk_objeto_usuario
FOREIGN KEY (ID_User)
REFERENCES Usuarios(ID_User);

ALTER TABLE Usuarios
ADD COLUMN is_posto BOOLEAN DEFAULT FALSE;

ALTER TABLE Usuarios
ADD COLUMN posto_id INTEGER;

ALTER TABLE Usuarios
ADD CONSTRAINT fk_usuario_posto
FOREIGN KEY (posto_id)
REFERENCES Posto_retirada(ID_posto);